# Wind Statistics

### Introduction:

The data have been modified to contain some missing values, identified by NaN.  
Using pandas should make this exercise
easier, in particular for the bonus question.

You should be able to perform all of these operations without using
a for loop or other looping construct.


1. The data in 'wind.data' has the following format:

In [144]:
"""
Yr Mo Dy   RPT   VAL   ROS   KIL   SHA   BIR   DUB   CLA   MUL   CLO   BEL   MAL
61  1  1 15.04 14.96 13.17  9.29   NaN  9.87 13.67 10.25 10.83 12.58 18.50 15.04
61  1  2 14.71   NaN 10.83  6.50 12.62  7.67 11.50 10.04  9.79  9.67 17.54 13.83
61  1  3 18.50 16.88 12.33 10.13 11.17  6.17 11.25   NaN  8.50  7.67 12.75 12.71
"""

'\nYr Mo Dy   RPT   VAL   ROS   KIL   SHA   BIR   DUB   CLA   MUL   CLO   BEL   MAL\n61  1  1 15.04 14.96 13.17  9.29   NaN  9.87 13.67 10.25 10.83 12.58 18.50 15.04\n61  1  2 14.71   NaN 10.83  6.50 12.62  7.67 11.50 10.04  9.79  9.67 17.54 13.83\n61  1  3 18.50 16.88 12.33 10.13 11.17  6.17 11.25   NaN  8.50  7.67 12.75 12.71\n'

   The first three columns are year, month and day.  The
   remaining 12 columns are average windspeeds in knots at 12
   locations in Ireland on that day.   

   More information about the dataset go [here](wind.desc).

### Step 1. Import the necessary libraries

In [145]:
import pandas as pd

### Step 2. Import the dataset from this [address](https://raw.githubusercontent.com/thieu1995/csv-files/main/data/pandas/wind.data)

### Step 3. Assign it to a variable called data and replace the first 3 columns by a proper datetime index.

In [146]:
def date_parser(x):
    return pd.to_datetime(f"19{x.iloc[0]} {x.iloc[1]} {x.iloc[2]}", format="%Y %m %d")

In [147]:
data = pd.read_csv("../../Datasets/wind.data", sep="\s+")
data["date"] = data[["Yr", "Mo", "Dy"]].apply(date_parser, axis=1)
data = data.drop(columns=["Yr", "Mo", "Dy"])
data

,RPT,VAL,ROS,KIL,SHA,BIR,DUB,CLA,MUL,CLO,BEL,MAL,date
0,15.04,14.96,13.17,9.29,NaN,9.87,13.67,10.25,10.83,12.58,18.50,15.04,1961-01-01
1,14.71,NaN,10.83,6.50,12.62,7.67,11.50,10.04,9.79,9.67,17.54,13.83,1961-01-02
2,18.50,16.88,12.33,10.13,11.17,6.17,11.25,NaN,8.50,7.67,12.75,12.71,1961-01-03
3,10.58,6.63,11.75,4.58,4.54,2.88,8.63,1.79,5.83,5.88,5.46,10.88,1961-01-04
4,13.33,13.25,11.42,6.17,10.71,8.21,11.92,6.54,10.92,10.34,12.92,11.83,1961-01-05
...,...,...,...,...,...,...,...,...,...,...,...,...,...
6569,17.58,16.96,17.62,8.08,13.21,11.67,14.46,15.59,14.04,14.00,17.21,40.08,1978-12-27
6570,13.21,5.46,13.46,5.00,8.12,9.42,14.33,16.25,15.25,18.05,21.79,41.46,1978-12-28
6571,14.00,10.29,14.42,8.71,9.71,10.54,19.17,12.46,14.50,16.42,18.88,29.58,1978-12-29
6572,18.50,14.04,21.29,9.13,12.75,9.71,18.08,12.87,12.46,12.12,14.67,28.79,1978-12-30
6573,20.33,17.41,27.29,9.59,12.08,10.13,19.25,11.63,11.58,11.38,12.08,22.08,1978-12-31

### Step 4. Year 2061? Do we really have data from this year? Create a function to fix it and apply it.

In [148]:
"I've already done this in the previous step :))"

"I've already done this in the previous step :))"

### Step 5. Set the right dates as the index. Pay attention at the data type, it should be datetime64[ns].

In [149]:
data = data.set_index("date")
data

,RPT,VAL,ROS,KIL,SHA,BIR,DUB,CLA,MUL,CLO,BEL,MAL
date,,,,,,,,,,,,
1961-01-01,15.04,14.96,13.17,9.29,NaN,9.87,13.67,10.25,10.83,12.58,18.50,15.04
1961-01-02,14.71,NaN,10.83,6.50,12.62,7.67,11.50,10.04,9.79,9.67,17.54,13.83
1961-01-03,18.50,16.88,12.33,10.13,11.17,6.17,11.25,NaN,8.50,7.67,12.75,12.71
1961-01-04,10.58,6.63,11.75,4.58,4.54,2.88,8.63,1.79,5.83,5.88,5.46,10.88
1961-01-05,13.33,13.25,11.42,6.17,10.71,8.21,11.92,6.54,10.92,10.34,12.92,11.83
...,...,...,...,...,...,...,...,...,...,...,...,...
1978-12-27,17.58,16.96,17.62,8.08,13.21,11.67,14.46,15.59,14.04,14.00,17.21,40.08
1978-12-28,13.21,5.46,13.46,5.00,8.12,9.42,14.33,16.25,15.25,18.05,21.79,41.46
1978-12-29,14.00,10.29,14.42,8.71,9.71,10.54,19.17,12.46,14.50,16.42,18.88,29.58
1978-12-30,18.50,14.04,21.29,9.13,12.75,9.71,18.08,12.87,12.46,12.12,14.67,28.79
1978-12-31,20.33,17.41,27.29,9.59,12.08,10.13,19.25,11.63,11.58,11.38,12.08,22.08

### Step 6. Compute how many values are missing for each location over the entire record.  
#### They should be ignored in all calculations below.

In [150]:
data.isnull().sum()

RPT    6
VAL    3
ROS    2
KIL    5
SHA    2
BIR    0
DUB    3
CLA    2
MUL    3
CLO    1
BEL    0
MAL    4
dtype: int64

In [151]:
data.dropna(inplace=True)

### Step 7. Compute how many non-missing values there are in total.

In [152]:
data.notnull().sum()

RPT    6546
VAL    6546
ROS    6546
KIL    6546
SHA    6546
BIR    6546
DUB    6546
CLA    6546
MUL    6546
CLO    6546
BEL    6546
MAL    6546
dtype: int64

### Step 8. Calculate the mean windspeeds of the windspeeds over all the locations and all the times.
#### A single number for the entire dataset.

In [153]:
data.mean().mean()

10.222465245951726

### Step 9. Create a DataFrame called loc_stats and calculate the min, max and mean windspeeds and standard deviations of the windspeeds at each location over all the days 

#### A different set of numbers for each location.

In [154]:
# Step 9. Create a DataFrame called loc_stats and calculate the min, max and mean windspeeds and standard deviations of the windspeeds at each location over all the days
loc_stats = pd.DataFrame({
    "min": data.min(),
    "max": data.max(),
    "mean": data.mean(),
    "std": data.std()
})
loc_stats

      min    max       mean       std
RPT  0.67  35.80  12.359979  5.618805
VAL  0.21  33.37  10.640267  5.268695
ROS  1.50  33.84  11.656396  5.007805
KIL  0.00  28.46   6.298587  3.600942
SHA  0.13  37.54  10.448923  4.933988
BIR  0.00  26.16   7.085066  3.967735
DUB  0.00  30.37   9.793006  4.978030
CLA  0.00  31.08   8.486601  4.498299
MUL  0.00  25.88   8.490257  4.165947
CLO  0.04  28.21   8.696705  4.500488
BEL  0.13  42.38  13.110668  5.829054
MAL  0.67  42.54  15.603129  6.702178

### Step 10. Create a DataFrame called day_stats and calculate the min, max and mean windspeed and standard deviations of the windspeeds across all the locations at each day.

#### A different set of numbers for each day.

In [ ]:
day_stats = pd.DataFrame({
    "min": data.min(axis=1),
    "max": data.max(axis=1),
    "mean": data.mean(axis=1),
    "std": data.std(axis=1)
})
day_stats

             min    max       mean       std
date
1961-01-04  1.79  11.75   6.619167  3.198126
1961-01-05  6.17  13.33  10.630000  2.445356
1961-01-06  4.42  13.21   8.240000  2.998063
1961-01-07  4.96  14.29  10.385000  3.072114
1961-01-08  5.91  16.62  10.487500  3.547237
...          ...    ...        ...       ...
1978-12-27  8.08  40.08  16.708333  7.868076
1978-12-28  5.00  41.46  15.150000  9.687857
1978-12-29  8.71  29.58  14.890000  5.756836
1978-12-30  9.13  28.79  15.367500  5.540437
1978-12-31  9.59  27.29  15.402500  5.702483

[6546 rows x 4 columns]

### Step 11. Find the average windspeed in January for each location.  
#### Treat January 1961 and January 1962 both as January.

In [ ]:
data[data.index.month == 1].mean()

RPT    14.831609
VAL    12.885389
ROS    13.276275
KIL     7.152477
SHA    11.644467
BIR     8.030561
DUB    11.788336
CLA     9.486962
MUL     9.511501
CLO    10.024069
BEL    14.527848
MAL    18.041826
dtype: float64

### Step 12. Downsample the record to a yearly frequency for each location.

In [ ]:
data.resample("Y").mean()

,RPT,VAL,ROS,KIL,SHA,BIR,DUB,CLA,MUL,CLO,BEL,MAL
date,,,,,,,,,,,,
1961-12-31,12.207588,10.207206,11.282853,6.846441,10.742735,7.617147,9.633265,8.684912,8.571941,9.700471,13.271559,13.587206
1962-12-31,12.274779,10.150856,11.714365,6.964337,10.692265,7.415331,11.043122,8.829807,8.335552,9.693812,12.985691,14.361436
1963-12-31,12.813452,10.836986,12.541151,7.330055,11.724110,8.434712,11.075699,10.336548,8.903589,10.224438,13.638877,14.999014
1964-12-31,12.363661,10.920164,12.104372,6.787787,11.454481,7.570874,10.259153,9.467350,7.789016,10.207951,13.740546,14.910301
1965-12-31,12.451370,11.075534,11.848767,6.858466,11.024795,7.478110,10.618712,8.879918,7.907425,9.918082,12.964247,15.591644
1966-12-31,13.461973,11.557205,12.020630,7.345726,11.805041,7.793671,10.579808,8.835096,8.514438,9.768959,14.265836,16.307260
1967-12-31,12.737151,10.990986,11.739397,7.143425,11.630740,7.368164,10.652027,9.325616,8.645014,9.547425,14.774548,17.135945
1968-12-31,11.835628,10.468197,11.409754,6.477678,10.760765,6.067322,8.859180,8.255519,7.224945,7.832978,12.808634,15.017486
1969-12-31,11.166356,9.723699,10.902000,5.767973,9.873918,6.189973,8.564493,7.711397,7.924521,7.754384,12.621233,15.762904
1970-12-31,12.600329,10.726932,11.730247,6.217178,10.567370,7.609452,9.609890,8.334630,9.297616,8.289808,13.183644,16.456027
1971-12-31,11.273123,9.095178,11.088329,5.241507,9.440329,6.097151,8.385890,6.757315,7.915370,7.229753,12.208932,15.025233
1972-12-31,12.463962,10.561311,12.058333,5.929699,9.430410,6.358825,9.704508,7.680792,8.357295,7.515273,12.727377,15.028716
1973-12-31,11.828466,10.680493,10.680493,5.547863,9.640877,6.548740,8.482110,7.614274,8.245534,7.812411,12.169699,15.441096
1974-12-31,13.643096,11.811781,12.336356,6.427041,11.110986,6.809781,10.084603,9.896986,9.331753,8.736356,13.252959,16.947671
1975-12-31,12.008575,10.293836,11.564712,5.269096,9.190082,5.668521,8.562603,7.843836,8.797945,7.382822,12.631671,15.307863
1976-12-31,11.737842,10.203115,10.761230,5.109426,8.846339,6.311038,9.149126,7.146202,8.883716,7.883087,12.332377,15.471448
1977-12-31,13.099616,11.144493,12.627836,6.073945,10.003836,8.586438,11.523205,8.378384,9.098192,8.821616,13.459068,16.590849
1978-12-31,12.504356,11.044274,11.380000,6.082356,10.167233,7.650658,9.489342,8.800466,9.089753,8.301699,12.967397,16.771370

### Step 13. Downsample the record to a monthly frequency for each location.

In [158]:
data.resample("M").mean()

,RPT,VAL,ROS,KIL,SHA,BIR,DUB,CLA,MUL,CLO,BEL,MAL
date,,,,,,,,,,,,
1961-01-31,14.506154,11.225385,12.960385,6.840000,10.509231,8.174231,10.403077,8.670769,8.323462,9.490385,13.270000,14.341538
1961-02-28,16.401923,15.037308,14.470000,9.242692,13.778077,10.884615,11.868077,11.746154,11.748462,12.626538,18.165000,15.300769
1961-03-31,10.660000,11.097407,10.420000,7.100741,10.265556,8.580000,9.108519,9.329259,10.100000,10.989630,16.066296,15.418889
1961-04-30,10.722667,9.427667,9.998000,5.830667,8.435000,6.495000,6.925333,7.094667,7.342333,7.237000,11.147333,10.278333
1961-05-31,10.024643,8.495714,10.539286,5.992500,9.480357,6.633929,7.645714,8.206786,8.120714,8.534643,11.912143,11.911786
...,...,...,...,...,...,...,...,...,...,...,...,...
1978-08-31,9.645161,8.259355,9.032258,4.502903,7.368065,5.935161,5.650323,5.417742,7.241290,5.536774,10.466774,12.054194
1978-09-30,10.913667,10.895000,10.635000,5.725000,10.372000,9.278333,10.790333,9.583000,10.069333,8.939000,15.680333,19.391333
1978-10-31,9.897742,8.670968,9.295806,4.721290,8.525161,6.774194,8.115484,7.337742,8.297742,8.243871,13.776774,17.150000
1978-11-30,16.151667,14.802667,13.508000,7.317333,11.475000,8.743000,11.492333,9.657333,10.701333,10.676000,17.404667,20.723000
1978-12-31,16.175484,13.748065,15.635161,7.094839,11.398710,9.241613,12.077419,10.194839,10.616774,11.028710,13.859677,21.371613

### Step 14. Downsample the record to a weekly frequency for each location.

In [159]:
data.resample("W").mean()

,RPT,VAL,ROS,KIL,SHA,BIR,DUB,CLA,MUL,CLO,BEL,MAL
date,,,,,,,,,,,,
1961-01-08,12.316000,10.408000,10.050000,5.658000,8.506000,6.242000,10.936000,5.932000,8.150000,8.428000,11.416000,13.226000
1961-01-15,12.468571,8.967143,11.958571,4.630000,7.351429,5.072857,7.535714,6.820000,5.712857,7.571429,11.125714,11.024286
1961-01-22,12.100000,9.500000,11.681667,4.293333,8.966667,6.938333,7.828333,7.291667,5.891667,6.693333,9.993333,10.346667
1961-01-29,19.880000,14.846667,17.548333,11.916667,16.325000,14.016667,14.450000,14.311667,13.316667,14.921667,19.800000,22.388333
1961-02-05,16.827143,15.460000,12.618571,8.247143,13.361429,9.107143,12.204286,8.548571,9.821429,9.460000,14.012857,11.935714
...,...,...,...,...,...,...,...,...,...,...,...,...
1978-12-03,14.934286,11.232857,13.941429,5.565714,10.215714,8.618571,9.642857,7.685714,9.011429,9.547143,11.835714,18.728571
1978-12-10,20.740000,19.190000,17.034286,9.777143,15.287143,12.774286,14.437143,12.488571,13.870000,14.082857,18.517143,23.061429
1978-12-17,16.758571,14.692857,14.987143,6.917143,11.397143,7.272857,10.208571,7.967143,9.168571,8.565714,11.102857,15.562857
1978-12-24,11.155714,8.008571,13.172857,4.004286,7.825714,6.290000,7.798571,8.667143,7.151429,8.072857,11.845714,18.977143
1978-12-31,14.951429,11.801429,16.035714,6.507143,9.660000,8.620000,13.708571,10.477143,10.868571,11.471429,12.947143,26.844286

### Step 15. Calculate the min, max and mean windspeeds and standard deviations of the windspeeds across all locations for each week (assume that the first week starts on January 2 1961) for the first 52 weeks.

In [ ]:
data.resample("W").agg(["min", "max", "mean", "std"]).iloc[:52]

              RPT                                VAL                    \
              min    max       mean       std    min    max       mean
date
1961-01-08  10.58  13.50  12.316000  1.421418   6.63  14.29  10.408000
1961-01-15   9.04  19.75  12.468571  3.555392   3.54  12.08   8.967143
1961-01-22   4.92  17.75  12.100000  4.893064   3.42  14.37   9.500000
1961-01-29  13.62  25.04  19.880000  4.619061   9.96  20.79  14.846667
1961-02-05  10.58  24.21  16.827143  5.251408   9.46  24.21  15.460000
1961-02-12  16.00  24.54  19.684286  3.587677  11.54  21.42  16.417143
1961-02-19   6.04  22.50  14.956667  5.525210  11.63  20.17  15.008333
1961-02-26   7.79  25.80  15.221429  7.020716   7.08  21.50  13.625714
1961-03-05  10.96  13.33  11.824000  1.071742   8.83  17.00  12.956000
1961-03-12   4.88  14.79   9.376667  3.732263   8.08  16.96  11.195000
1961-03-19   4.92  16.88  11.911429  3.860036   9.46  15.54  13.501429
1961-03-26   6.29  15.00   9.567143  3.613298   2.58  11.63   8.387143
1961-04-02   5.88  18.25   9.818000  4.853908   3.50  16.29   7.684000
1961-04-09   4.50  18.12  11.964286  4.604392   7.04  14.62  10.654286
1961-04-16   4.71  15.50   8.965714  3.937727   4.83  12.25   8.000000
1961-04-23   4.00  21.09  12.621429  5.676655   3.71  15.41  10.438571
1961-04-30   4.08  16.29  10.117143  4.349662   6.50  14.46   9.798571
1961-05-07   9.87  23.00  15.367143  5.025507  10.29  19.79  13.970000
1961-05-14   3.54  12.79   7.901667  3.673850   3.96  11.54   7.645000
1961-05-21   4.88  15.04   8.561667  3.857369   3.58  10.17   5.631667
1961-05-28   4.96  10.92   7.550000  2.433828   3.67  11.17   6.536667
1961-06-04   7.00  15.92  10.321429  3.099701   4.75   9.79   7.407143
1961-06-11   8.29  14.42  10.917143  2.248597   6.83  11.54   8.992857
1961-06-18   6.13  14.33  10.571429  3.009482   4.12  14.54   9.565714
1961-06-25   4.00   9.00   7.345714  1.982035   3.25   9.50   6.108571
1961-07-02   7.21  13.13   9.826000  2.629340   6.34  11.42   8.310000
1961-07-09   7.29  17.50  11.806667  4.005984   3.75  10.75   7.221667
1961-07-16   8.63  22.50  16.680000  5.168710   7.87  19.29  13.518571
1961-07-23   3.04   5.88   4.202857  1.047978   2.92   6.79   4.255714
1961-07-30   6.13  16.08  10.561429  4.157641   4.63  13.79   8.445714
1961-08-06   7.67  16.08  10.870000  2.950887   5.09  15.79   8.792857
1961-08-13   2.88  14.21   9.928000  4.931346   4.42  10.00   8.026000
1961-08-20  13.13  18.91  15.471667  2.470590   7.25  13.62  10.513333
1961-08-27   7.67  18.16  12.391429  3.395857   6.87  14.58  11.430000
1961-09-03   3.63  14.46   8.678571  4.398615   1.13  22.00   8.821429
1961-09-10   5.00  17.62  10.541429  5.207278   3.04  13.59   8.798571
1961-09-17   5.33  28.75  17.160000  7.679190   7.12  22.08  14.440000
1961-09-24   6.92  10.25   8.291667  1.250191   2.92  13.62   7.645000
1961-10-01  10.34  19.12  14.850000  3.600911   6.96  13.62  11.361667
1961-10-08   3.13  16.08  11.250000  5.596710   3.63  16.96   8.757143
1961-10-15   3.71  17.12  10.881667  4.780675   6.13  13.25   9.905000
1961-10-22  10.46  28.62  19.260000  7.888314   3.75  19.46  13.364286
1961-10-29   4.33  21.34  14.353333  7.143390   2.75  17.00  10.303333
1961-11-05   5.88  15.79  11.571429  3.369201   3.96  13.46   9.590000
1961-11-12   5.46  16.08  10.428571  3.939811   5.50  10.75   7.690000
1961-11-19   7.50  15.00  10.798571  2.784358   4.21  13.00   7.951429
1961-11-26   5.75  14.29   9.638333  3.229622   3.29  11.79   6.886667
1961-12-03   7.92  23.75  12.608571  5.704669   4.67  18.71  10.442857
1961-12-10  10.83  23.71  17.362857  4.890152   9.21  21.37  14.362857
1961-12-17   9.29  21.34  14.985714  4.095106   8.63  17.62  13.472857
1961-12-24  11.46  24.41  15.757143  4.959717   9.79  16.13  11.971429
1961-12-31   5.04  20.54  13.634286  5.787783   3.08  16.04   9.504286

                        ROS         ...        CLO              BEL         \
                 std    min    max  ...       mean       std    min    max
date                                ...
1961-01-08  3.282076   7.62  11.75  ...   8.428000  1.959418   5.46  16.62
1961-01-15  3.148945   7.08  19.50  ...   7.571429  4.084293   5.25  20.71
1961-01-22  4.070420   7.29  17.33  ...   6.693333  3.203652   6.50  15.92
1961-01-29  4.242125  12.67  25.84  ...  14.921667  3.494638  14.04  26.08
1961-02-05  5.187395   9.04  19.70  ...   9.460000  2.839501   9.17  19.33
1961-02-12  3.608373  13.67  21.34  ...  14.440000  1.746749  15.21  26.38
1961-02-19  3.908818   6.13  19.41  ...  13.521667  2.772287  14.09  28.62
1961-02-26  5.147348   6.08  22.42  ...  12.730000  4.920064   9.59  23.21
1961-03-05  3.490319   8.17  13.67  ...  12.068000  1.729775  11.58  23.45
1961-03-12  3.359302   7.54  15.50  ...   9.570000  3.065864  10.21  22.71
1961-03-19  2.352867   5.25  13.96  ...  11.627143  3.099472  11.29  22.79
1961-03-26  3.657265   4.79  15.63  ...  11.481429  2.538224   8.25  21.34
1961-04-02  5.130656   5.09  14.96  ...   8.666000  3.193114   7.21  18.63
1961-04-09  2.845399   9.29  18.29  ...   7.238571  2.336182   7.62  17.16
1961-04-16  2.607118   3.92  15.79  ...   6.178571  2.161137   5.75  16.17
1961-04-23  4.631736   3.33  17.00  ...   9.551429  3.347972   6.75  19.21
1961-04-30  2.871425   2.54  14.96  ...   6.124286  2.840568   5.13  13.04
1961-05-07  3.750835   8.42  21.21  ...  11.585714  3.620819   4.79  28.08
1961-05-14  2.755749   4.63  12.33  ...   8.396667  5.745543   6.54  18.66
1961-05-21  2.468906   5.91  15.96  ...   6.855000  2.309283   6.63  12.00
1961-05-28  2.757025   3.58  13.13  ...   6.881667  2.089856   6.13  13.88
1961-06-04  1.868125   6.83  15.96  ...   9.035714  2.096989   8.71  17.00
1961-06-11  1.524836   6.04  11.58  ...   8.397143  2.158323   5.37  16.17
1961-06-18  3.509444   6.50  15.50  ...   9.594286  3.792400   7.29  25.25
1961-06-25  2.212460   5.13  10.37  ...  11.257143  2.286218  11.00  19.08
1961-07-02  2.169505   7.62   9.25  ...   9.716000  1.437891   6.96  19.92
1961-07-09  2.943083   7.62  14.92  ...  10.381667  3.977428   7.08  20.41
1961-07-16  3.849630   8.00  14.29  ...  10.157143  3.271899   5.04  20.25
1961-07-23  1.400010   4.08  12.67  ...   6.041429  1.439785   4.21  10.13
1961-07-30  3.203206   6.42  15.67  ...   9.470000  4.350268   7.87  22.17
1961-08-06  3.985226   5.54  15.59  ...   8.951429  2.903018   6.17  18.54
1961-08-13  2.410960   6.00  11.63  ...   7.632000  2.047833   9.83  14.00
1961-08-20  2.760092   9.17  14.04  ...  12.131667  2.972961   9.59  21.92
1961-08-27  3.174702   9.50  17.83  ...  12.507143  3.855302   5.75  23.38
1961-09-03  7.474025   2.42  12.75  ...   8.924286  3.993736   4.79  24.71
1961-09-10  4.003996   3.63  14.88  ...   7.565714  3.649278   5.41  15.83
1961-09-17  5.360585   7.29  26.50  ...  14.268571  5.128338  13.92  23.91
1961-09-24  3.495865   5.33  12.17  ...   6.896667  2.563058   4.54  20.96
1961-10-01  2.812482   7.87  17.16  ...  10.903333  3.310738   7.79  20.30
1961-10-08  5.060803   4.96  17.83  ...   7.662857  4.296870   4.79  17.83
1961-10-15  2.924338   4.21  20.96  ...  10.181667  3.364375   8.54  20.46
1961-10-22  5.998199   9.92  22.63  ...  16.461429  5.890511  10.88  24.71
1961-10-29  6.021514   4.79  22.88  ...  11.423333  5.257283   8.50  22.29
1961-11-05  3.900278   6.54  14.33  ...  11.864286  2.784450  10.29  20.17
1961-11-12  2.141191   3.83  20.41  ...   6.415714  2.843518   6.13  12.58
1961-11-19  3.208548   6.46  32.71  ...   6.031429  4.402588   0.71   9.59
1961-11-26  3.344994   5.04  14.46  ...  10.026667  2.720968   6.50  20.46
1961-12-03  5.107089   8.00  19.92  ...   7.911429  3.680477   5.50  19.04
1961-12-10  4.115506   9.71  20.54  ...  12.022857  4.156207  10.71  21.79
1961-12-17  3.587886   9.04  19.00  ...  11.058571  4.633398   5.50  22.83
1961-12-24  2.220866   8.08  22.13  ...   7.697143  4.637096   5.29  17.67
1961-12-31  4.566479   2.13  29.33  ...   7.701429  3.526625   3.75  13.21

                                   MAL
                 mean       std    min    max       mean       std
date
1961-01-08  11.416000  4.531918  10.88  16.46  13.226000  2.134978
1961-01-15  11.125714  5.552215   5.17  16.92  11.024286  4.692355
1961-01-22   9.993333  3.941358   6.79  16.08  10.346667  3.407132
1961-01-29  19.800000  4.675044  17.50  27.63  22.388333  4.224639
1961-02-05  14.012857  4.210858   7.17  19.25  11.935714  4.336104
1961-02-12  21.832857  4.063753  17.04  21.84  19.155714  1.828705
1961-02-19  19.756667  5.021524  10.96  22.58  15.925000  4.763632
1961-02-26  16.304286  5.091162   6.67  23.87  14.322857  6.182283
1961-03-05  17.174000  5.058249   8.83  17.54  14.108000  3.350772
1961-03-12  16.068333  4.408144   5.54  18.16  13.066667  4.956336
1961-03-19  19.350000  3.779727  11.34  22.95  16.227143  4.331958
1961-03-26  14.037143  4.318069  13.13  22.50  18.134286  3.701846
1961-04-02  12.094000  4.138965   7.17  16.83  12.910000  3.698547
1961-04-09  11.712857  3.147781   7.21  15.34  11.371429  2.598271
1961-04-16   9.482857  3.641464   5.66  12.87   8.690000  2.747842
1961-04-23  13.620000  4.735096   4.96  20.46  12.470000  5.908542
1961-04-30   9.720000  2.948237   2.67  17.50   8.637143  5.108365
1961-05-07  17.548571  8.003490   3.83  26.58  14.571429  7.728504
1961-05-14  10.386667  4.345856   3.33  26.30  10.530000  8.597707
1961-05-21   9.493333  2.130903   5.91  14.96  10.256667  3.476795
1961-05-28   9.883333  2.754572   8.00  17.04  10.883333  3.445685
1961-06-04  12.298571  2.611139  10.63  17.96  13.597143  2.593586
1961-06-11  10.148571  3.993062   5.96  19.83  12.250000  4.925055
1961-06-18  15.351429  6.477887   6.13  24.71  15.025714  6.242673
1961-06-25  14.370000  2.498386  13.75  21.50  17.410000  3.063011
1961-07-02  11.800000  5.171098   8.50  16.79  12.402000  4.016574
1961-07-09  11.700000  4.737155  12.08  21.29  15.750000  3.956322
1961-07-16  13.520000  4.971060   5.96  21.96  12.524286  4.974273
1961-07-23   7.524286  2.050218   5.41  10.92   8.415714  2.133994
1961-07-30  12.841429  5.580903   6.13  25.37  13.761429  6.664574
1961-08-06  11.595714  4.901377   9.08  20.25  13.760000  4.448251
1961-08-13  11.274000  1.882254   5.88  15.16   9.858000  3.697340
1961-08-20  14.848333  4.471570  13.04  24.30  16.626667  3.934238
1961-08-27  16.251429  6.711322   8.29  22.29  16.485714  4.947608
1961-09-03  13.664286  7.678051   5.41  22.54  11.022857  6.308087
1961-09-10  10.700000  4.220584   3.37  20.25  11.034286  6.049619
1961-09-17  19.878571  4.464252  14.67  33.09  18.984286  6.332885
1961-09-24  11.653333  5.432553   5.25  14.62   9.915000  3.398163
1961-10-01  15.348333  4.988901   4.04  16.21  12.701667  4.802201
1961-10-08   8.810000  4.800403   4.83  19.62  11.410000  5.462002
1961-10-15  14.783333  4.401903  11.96  21.04  16.011667  3.925249
1961-10-22  17.477143  5.645871  13.46  33.45  23.641429  7.468377
1961-10-29  13.643333  5.274629   9.83  25.12  16.325000  6.867864
1961-11-05  16.322857  4.038493  13.37  23.58  19.195714  3.870800
1961-11-12   9.208571  2.532196   5.71  15.54  10.858571  3.690752
1961-11-19   5.875714  3.643285   2.00  13.25   5.737143  3.787654
1961-11-26  11.971667  5.895223   8.71  22.58  14.146667  5.790840
1961-12-03  11.464286  5.552648   5.88  21.29  14.725714  5.233192
1961-12-10  15.975714  4.667933   7.58  29.33  16.241429  7.345893
1961-12-17  15.112857  6.531043   6.50  21.12  14.644286  5.665006
1961-12-24   9.958571  5.065308   2.62  16.62   8.164286  5.048035
1961-12-31   9.697143  3.262217   6.63  15.21  12.840000  3.012729

[52 rows x 48 columns]